import datetime
print('datetime.datetime.today():')
print(datetime.datetime.today())
date_today = datetime.date.today()
print('datetime.date.today():')
print(datetime.date.today())
print('datetime.date.today().year:')
print(datetime.date.today().year)
print('datetime.date.today().month for Month in digit format:')
print(datetime.date.today().month)
print("datetime.date.today().strftime('%B') for month in String foramt:")
print(datetime.date.today().strftime('%B'))
print('datetime.date.today().day for day in Month in digit foramt:')
print(datetime.date.today().day)
print("datetime.date.today().strftime('%A') for Week Day in String foramt:")
print(datetime.date.today().strftime('%A'))